version: "2"
services:
  #MySQL Database image
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql:/var/lib/mysql

  #WordPress image based on Apache
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - "./wordpress:/var/www/html"
volumes:
  mysql: {}
