apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
